### ISSUE TITLE
Update or remove Ground Station

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/SRAD-Avionics#114]
Now that the Ground Station exists in its own repo on the Terrapin-Rocket-Team account, having the a separate copy in the Side_Projects folder in this repo is somewhat redundant. The original reason for this was to give people easy access to it since it had been on my personal account. My thought is that it should either be turned into a git submodule so that updates to the Ground Station are automatically added here, or just removed entirely.

**Comment by varun-un** [comment]
Submoduling is probably ideal I would think. There might be a way as well to configure git to by default exclude cloning submodules unless specified to avoid having everyone need to copy over the entire ground station if they don't want.
