### ISSUE TITLE
Enhance Sensor Board for v1.1

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/SRAD-Avionics#119]
Look to potentially add the following to the sensor board:

- [ ] I2C connections for COTS sensors 
- [ ] Add LEDs to data lines from IC chips to indicate transmissions or fixes
- [ ] Fix issues with v1.0 from testing

**Comment by DrewBrandt** [comment]
I think there might be an issue with the LEDs as unlinke SPI where each IC has its own CS pin, I2C has a unified bus, so we would only know about comms on the bus, not comms between specific ICs
