### ISSUE TITLE
Design On-The-Ground Radio Teensy Code

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/SRAD-Avionics#67]
This code should be able to synchronize and transmit the 3 streams of data from 2 live video sources and 1 telemetry source in real-time over Serial to a laptop's USB port for processing by the Ground Station. This should be done with minimal overhead and quick enough that all radio data gets transmitted seamlessly

**Comment by varun-un** [comment]
Will also need Ground Station code developed in tandem to decipher and separate out the streams of data

**Comment by jhauerst** [comment]
@varun-un I believe this code is completed, has it been merged in yet?
