### ISSUE TITLE
Begin implementation of platform agnostic sensor code

### ISSUE THREAD

**Issue by DrewBrandt** [Terrapin-Rocket-Team/SRAD-Avionics#76]
Following on from #25, #26, and #27, begin planning out what a portable flight code project would look like.

**Comment by DrewBrandt** [comment]
I think this may take on the from of some kind of intermediary that we write that can detect the platform and use the appropriate low level libraries. I'm doing some research on it now.

**Comment by DrewBrandt** [comment]
I expect this to be a long-term project that is basically on this branch for a few months. I'm going to re-arrange a few files and add some folders to this branch to make things a bit easier to manage as I change and test stuff.

**Comment by DrewBrandt** [comment]
Update: Code compiles and runs on the STM32 dev board we got. Next step is designing a custom STM board, i.e. #83

**Comment by varun-un** [comment]
Closing as this becomes a more MMFS issue
